name: Transport Post-merge pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: go get ./...
      - run: |
          go install github.com/axw/gocov/gocov
          go install github.com/AlekSi/gocov-xml
      - run: |
          go test -v -coverprofile cover.out ./...
          gocov convert cover.out | gocov-xml > coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
